version: '3'
services:
  app:
    restart: always
    build: .
    tty: true
    volumes:
      - ./:/src
  qdrant:
    image: qdrant/qdrant:v1.2.2
    ports:
    - 6333:6333
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
